import Testing

@testable import SwiftGeneratorKit

@Suite("SwiftGenerator")
struct SwiftGeneratorTests {
	let sut = SwiftGenerator(moduleName: "ChallengeCharacter")
	let publicSut = SwiftGenerator(moduleName: "ChallengeCore")

	// MARK: - Mock Naming

	@Test("Strips Contract suffix from mock name")
	func stripsContractSuffix() {
		let proto = makeProto(name: "FooTrackerContract")
		let result = sut.generate(from: proto)

		#expect(result.contains("final class FooTrackerMock: FooTrackerContract {"))
	}

	@Test("Strips Delegate suffix from mock name")
	func stripsDelegateSuffix() {
		let proto = makeProto(name: "FooDelegate")
		let result = sut.generate(from: proto)

		#expect(result.contains("final class FooMock: FooDelegate {"))
	}

	@Test("Keeps name without known suffix")
	func keepsNameWithoutSuffix() {
		let proto = makeProto(name: "FooTracker")
		let result = sut.generate(from: proto)

		#expect(result.contains("final class FooTrackerMock: FooTracker {"))
	}

	// MARK: - Header

	@Test("Adds auto-generated header comment")
	func addsAutoGeneratedHeader() {
		let proto = makeProto(name: "FooContract")
		let result = sut.generate(from: proto)

		#expect(result.hasPrefix("// Auto-generated by SwiftGenerator — DO NOT EDIT.\n// Any changes will be overwritten the next time mocks are regenerated.\n"))
	}

	// MARK: - Periphery Ignore

	@Test("Adds periphery:ignore:all comment")
	func addsPeripheryIgnore() {
		let proto = makeProto(name: "FooContract")
		let result = sut.generate(from: proto)

		#expect(result.contains("// periphery:ignore:all"))
	}

	// MARK: - MainActor Pattern

	@Test("Generates MainActor mock for tracker with void methods")
	func mainActorTracker() {
		let proto = ProtocolMetadata(
			name: "FooTrackerContract",
			accessLevel: "",
			isNonisolated: false,
			inheritedTypes: [],
			methods: [
				MethodMetadata(
					name: "trackScreenViewed",
					parameters: [],
					returnType: nil,
					isAsync: false,
					isThrowing: false,
					throwsType: nil,
					isConcurrent: false,
					hasGenericReturn: false,
					genericClause: nil
				),
				MethodMetadata(
					name: "trackItemSelected",
					parameters: [ParameterMetadata(externalLabel: nil, internalName: "identifier", type: "Int")],
					returnType: nil,
					isAsync: false,
					isThrowing: false,
					throwsType: nil,
					isConcurrent: false,
					hasGenericReturn: false,
					genericClause: nil
				),
			],
			properties: [],
			sourceFilePath: ""
		)

		let result = sut.generate(from: proto)

		// Class declaration
		#expect(result.contains("final class FooTrackerMock: FooTrackerContract {"))
		#expect(!result.contains("@unchecked Sendable"))

		// trackScreenViewed properties
		#expect(result.contains("private(set) var trackScreenViewedCallsCount = 0"))
		#expect(result.contains("var trackScreenViewedClosure: (() -> Void)?"))

		// trackItemSelected properties
		#expect(result.contains("private(set) var trackItemSelectedCallsCount = 0"))
		#expect(result.contains("private(set) var trackItemSelectedReceivedIdentifier: Int?"))
		#expect(result.contains("private(set) var trackItemSelectedReceivedInvocations: [Int] = []"))
		#expect(result.contains("var trackItemSelectedClosure: (() -> Void)?"))

		// No ThrowableError or ReturnValue for void non-throwing
		#expect(!result.contains("ThrowableError"))
		#expect(!result.contains("ReturnValue"))

		// Method bodies
		#expect(result.contains("trackScreenViewedCallsCount += 1"))
		#expect(result.contains("trackScreenViewedClosure?()"))
		#expect(result.contains("trackItemSelectedCallsCount += 1"))
		#expect(result.contains("trackItemSelectedReceivedIdentifier = identifier"))
		#expect(result.contains("trackItemSelectedReceivedInvocations.append(identifier)"))
		#expect(result.contains("trackItemSelectedClosure?()"))
	}

	@Test("Generates MainActor mock with Result ReturnValue for typed-throws UseCase")
	func mainActorWithSendable() {
		let proto = ProtocolMetadata(
			name: "GetFooUseCaseContract",
			accessLevel: "",
			isNonisolated: false,
			inheritedTypes: ["Sendable"],
			methods: [
				MethodMetadata(
					name: "execute",
					parameters: [ParameterMetadata(externalLabel: nil, internalName: "identifier", type: "Int")],
					returnType: "String",
					isAsync: true,
					isThrowing: true,
					throwsType: "FooError",
					isConcurrent: false,
					hasGenericReturn: false,
					genericClause: nil
				),
			],
			properties: [],
			sourceFilePath: ""
		)

		let result = sut.generate(from: proto)

		#expect(result.contains("final class GetFooUseCaseMock: GetFooUseCaseContract, @unchecked Sendable {"))

		// Properties — Result<T, E> for ReturnValue, simple Closure
		#expect(result.contains("private(set) var executeCallsCount = 0"))
		#expect(result.contains("private(set) var executeReceivedIdentifier: Int?"))
		#expect(result.contains("private(set) var executeReceivedInvocations: [Int] = []"))
		#expect(result.contains("var executeReturnValue: Result<String, FooError>?"))
		#expect(result.contains("var executeClosure: (() async -> Void)?"))

		// No separate ThrowableError or computed Result
		#expect(!result.contains("executeThrowableError"))
		#expect(!result.contains("var executeResult:"))

		// Method signature
		#expect(result.contains("func execute(identifier: Int) async throws(FooError) -> String"))

		// Method body — await closure then Result.get()
		#expect(result.contains("await executeClosure?()"))
		#expect(result.contains("guard let returnValue = executeReturnValue"))
		#expect(result.contains("return try returnValue.get()"))
	}

	// MARK: - Nonisolated Pattern

	@Test("Generates nonisolated mock with Result ReturnValue for untyped-throws data source")
	func nonisolatedDataSource() {
		let proto = ProtocolMetadata(
			name: "FooRemoteDataSourceContract",
			accessLevel: "",
			isNonisolated: true,
			inheritedTypes: ["Sendable"],
			methods: [
				MethodMetadata(
					name: "fetch",
					parameters: [ParameterMetadata(externalLabel: nil, internalName: "identifier", type: "Int")],
					returnType: "String",
					isAsync: true,
					isThrowing: true,
					throwsType: nil,
					isConcurrent: true,
					hasGenericReturn: false,
					genericClause: nil
				),
			],
			properties: [],
			sourceFilePath: ""
		)

		let result = sut.generate(from: proto)

		// Class declaration
		#expect(result.contains("nonisolated final class FooRemoteDataSourceMock: FooRemoteDataSourceContract, @unchecked Sendable {"))

		// Properties — Result<T, any Error> for untyped throws
		#expect(result.contains("private(set) var fetchCallsCount = 0"))
		#expect(result.contains("private(set) var fetchReceivedIdentifier: Int?"))
		#expect(result.contains("private(set) var fetchReceivedInvocations: [Int] = []"))
		#expect(result.contains("var fetchReturnValue: Result<String, any Error>?"))
		#expect(result.contains("var fetchClosure: (() async -> Void)?"))

		// No separate ThrowableError
		#expect(!result.contains("fetchThrowableError"))

		// Method signature
		#expect(result.contains("@concurrent func fetch(identifier: Int) async throws -> String"))

		// Method body
		#expect(result.contains("await fetchClosure?()"))
		#expect(result.contains("return try returnValue.get()"))
	}

	@Test("Generates nonisolated mock with typed throws Result ReturnValue")
	func nonisolatedTypedThrows() {
		let proto = ProtocolMetadata(
			name: "FooRepositoryContract",
			accessLevel: "",
			isNonisolated: true,
			inheritedTypes: ["Sendable"],
			methods: [
				MethodMetadata(
					name: "getItem",
					parameters: [
						ParameterMetadata(externalLabel: nil, internalName: "identifier", type: "Int"),
						ParameterMetadata(externalLabel: nil, internalName: "cachePolicy", type: "CachePolicy"),
					],
					returnType: "Item",
					isAsync: true,
					isThrowing: true,
					throwsType: "ItemError",
					isConcurrent: true,
					hasGenericReturn: false,
					genericClause: nil
				),
			],
			properties: [],
			sourceFilePath: ""
		)

		let result = sut.generate(from: proto)

		// Multiple params use ReceivedArguments tuple
		#expect(result.contains("private(set) var getItemReceivedArguments: (identifier: Int, cachePolicy: CachePolicy)?"))
		#expect(result.contains("private(set) var getItemReceivedInvocations: [(identifier: Int, cachePolicy: CachePolicy)] = []"))
		#expect(result.contains("var getItemReturnValue: Result<Item, ItemError>?"))
		#expect(result.contains("var getItemClosure: (() async -> Void)?"))

		// No separate ThrowableError
		#expect(!result.contains("getItemThrowableError"))

		// Method signature
		#expect(result.contains("@concurrent func getItem(identifier: Int, cachePolicy: CachePolicy) async throws(ItemError) -> Item"))

		// Method body records arguments as tuple
		#expect(result.contains("getItemReceivedArguments = (identifier, cachePolicy)"))
		#expect(result.contains("getItemReceivedInvocations.append((identifier, cachePolicy))"))
		#expect(result.contains("return try returnValue.get()"))
	}

	@Test("Generates nonisolated mock for non-throwing async method")
	func nonisolatedNonThrowing() {
		let proto = ProtocolMetadata(
			name: "FooRepositoryContract",
			accessLevel: "",
			isNonisolated: true,
			inheritedTypes: ["Sendable"],
			methods: [
				MethodMetadata(
					name: "getSearches",
					parameters: [],
					returnType: "[String]",
					isAsync: true,
					isThrowing: false,
					throwsType: nil,
					isConcurrent: true,
					hasGenericReturn: false,
					genericClause: nil
				),
				MethodMetadata(
					name: "saveSearch",
					parameters: [ParameterMetadata(externalLabel: "_", internalName: "query", type: "String")],
					returnType: nil,
					isAsync: true,
					isThrowing: false,
					throwsType: nil,
					isConcurrent: true,
					hasGenericReturn: false,
					genericClause: nil
				),
			],
			properties: [],
			sourceFilePath: ""
		)

		let result = sut.generate(from: proto)

		// getSearches — non-throwing, plain ReturnValue
		#expect(result.contains("var getSearchesReturnValue: [String]?"))
		#expect(result.contains("var getSearchesClosure: (() async -> Void)?"))
		#expect(!result.contains("getSearchesThrowableError"))

		// saveSearch — single param tracking
		#expect(result.contains("@concurrent func saveSearch(_ query: String) async"))
		#expect(result.contains("saveSearchReceivedQuery: String?"))
		#expect(result.contains("saveSearchReceivedInvocations: [String] = []"))
		#expect(result.contains("var saveSearchClosure: (() async -> Void)?"))
	}

	// MARK: - Actor Pattern

	@Test("Generates actor mock with setter methods for local data source")
	func actorDataSource() {
		let proto = ProtocolMetadata(
			name: "FooLocalDataSourceContract",
			accessLevel: "",
			isNonisolated: false,
			inheritedTypes: ["Actor"],
			methods: [
				MethodMetadata(
					name: "getValue",
					parameters: [ParameterMetadata(externalLabel: nil, internalName: "identifier", type: "Int")],
					returnType: "String?",
					isAsync: false,
					isThrowing: false,
					throwsType: nil,
					isConcurrent: false,
					hasGenericReturn: false,
					genericClause: nil
				),
				MethodMetadata(
					name: "saveValue",
					parameters: [ParameterMetadata(externalLabel: "_", internalName: "value", type: "String")],
					returnType: nil,
					isAsync: false,
					isThrowing: false,
					throwsType: nil,
					isConcurrent: false,
					hasGenericReturn: false,
					genericClause: nil
				),
			],
			properties: [],
			sourceFilePath: ""
		)

		let result = sut.generate(from: proto)

		// Actor declaration
		#expect(result.contains("actor FooLocalDataSourceMock: FooLocalDataSourceContract {"))

		// getValue properties
		#expect(result.contains("private(set) var getValueCallsCount = 0"))
		#expect(result.contains("private(set) var getValueReceivedIdentifier: Int?"))
		#expect(result.contains("var getValueReturnValue: String?"))
		#expect(result.contains("var getValueClosure: (() -> Void)?"))

		// Actor setter methods — simple closure type
		#expect(result.contains("func setGetValueReturnValue(_ value: String?)"))
		#expect(result.contains("func setGetValueClosure(_ closure: (() -> Void)?)"))
		#expect(result.contains("func setSaveValueClosure(_ closure: (() -> Void)?)"))

		// Method bodies
		#expect(result.contains("saveValueCallsCount += 1"))
		#expect(result.contains("saveValueReceivedValue = value"))
		#expect(result.contains("return getValueReturnValue"))
	}

	// MARK: - Public Access

	@Test("Generates public mock with correct access modifiers")
	func publicMock() {
		let proto = ProtocolMetadata(
			name: "NavigatorContract",
			accessLevel: "public",
			isNonisolated: false,
			inheritedTypes: [],
			methods: [
				MethodMetadata(
					name: "navigate",
					parameters: [ParameterMetadata(externalLabel: "to", internalName: "destination", type: "String")],
					returnType: nil,
					isAsync: false,
					isThrowing: false,
					throwsType: nil,
					isConcurrent: false,
					hasGenericReturn: false,
					genericClause: nil
				),
			],
			properties: [],
			sourceFilePath: ""
		)

		let result = publicSut.generate(from: proto)

		#expect(result.contains("import ChallengeCore"))
		#expect(!result.contains("@testable"))
		#expect(result.contains("public final class NavigatorMock: NavigatorContract {"))

		// Public properties — simple closure
		#expect(result.contains("public private(set) var navigateCallsCount = 0"))
		#expect(result.contains("public private(set) var navigateReceivedDestination: String?"))
		#expect(result.contains("public private(set) var navigateReceivedInvocations: [String] = []"))
		#expect(result.contains("public var navigateClosure: (() -> Void)?"))

		// Public method and init
		#expect(result.contains("public func navigate(to destination: String)"))
		#expect(result.contains("public init() {}"))
	}

	// MARK: - Properties

	@Test("Generates mock with protocol properties and init")
	func protocolProperties() {
		let proto = ProtocolMetadata(
			name: "FooDelegate",
			accessLevel: "",
			isNonisolated: false,
			inheritedTypes: ["AnyObject", "Sendable"],
			methods: [
				MethodMetadata(
					name: "didApply",
					parameters: [ParameterMetadata(externalLabel: "_", internalName: "value", type: "String")],
					returnType: nil,
					isAsync: false,
					isThrowing: false,
					throwsType: nil,
					isConcurrent: false,
					hasGenericReturn: false,
					genericClause: nil
				),
			],
			properties: [
				PropertyMetadata(name: "currentValue", type: "String", isSettable: false),
			],
			sourceFilePath: ""
		)

		let result = sut.generate(from: proto)

		#expect(result.contains("final class FooMock: FooDelegate, @unchecked Sendable {"))
		#expect(result.contains("var currentValue: String"))
		#expect(result.contains("init(currentValue: String)"))
		#expect(result.contains("self.currentValue = currentValue"))
	}

	// MARK: - Imports

	@Test("Uses @testable import for internal mocks")
	func testableImport() {
		let proto = makeProto(name: "FooContract")
		let result = sut.generate(from: proto)

		#expect(result.contains("@testable import ChallengeCharacter"))
	}

	@Test("Uses regular import for public mocks")
	func regularImport() {
		let proto = ProtocolMetadata(
			name: "FooContract",
			accessLevel: "public",
			isNonisolated: false,
			inheritedTypes: [],
			methods: [],
			properties: [],
			sourceFilePath: ""
		)

		let result = publicSut.generate(from: proto)

		#expect(result.contains("import ChallengeCore"))
		#expect(!result.contains("@testable"))
	}

	// MARK: - Generic Methods

	@Test("Generates mock for generic method with Any-based properties")
	func genericMethod() {
		let proto = ProtocolMetadata(
			name: "FooClientContract",
			accessLevel: "",
			isNonisolated: false,
			inheritedTypes: ["Sendable"],
			methods: [
				MethodMetadata(
					name: "execute",
					parameters: [ParameterMetadata(externalLabel: "_", internalName: "operation", type: "String")],
					returnType: "T",
					isAsync: true,
					isThrowing: true,
					throwsType: nil,
					isConcurrent: false,
					hasGenericReturn: true,
					genericClause: "<T: Decodable>"
				),
			],
			properties: [],
			sourceFilePath: ""
		)

		let result = sut.generate(from: proto)

		// Generic return uses Any? for ReturnValue (not Result)
		#expect(result.contains("var executeReturnValue: Any?"))
		#expect(result.contains("var executeClosure: (() async -> Void)?"))

		// Method signature preserves generic clause
		#expect(result.contains("func execute<T: Decodable>(_ operation: String) async throws -> T"))

		// Return value casts from Any to T
		#expect(result.contains("guard let returnValue = executeReturnValue as? T"))
	}

	// MARK: - Reset

	@Test("Generates reset that clears only tracking properties")
	func resetOnlyClearsTracking() {
		let proto = ProtocolMetadata(
			name: "FooTrackerContract",
			accessLevel: "",
			isNonisolated: false,
			inheritedTypes: [],
			methods: [
				MethodMetadata(
					name: "trackScreenViewed",
					parameters: [],
					returnType: nil,
					isAsync: false,
					isThrowing: false,
					throwsType: nil,
					isConcurrent: false,
					hasGenericReturn: false,
					genericClause: nil
				),
				MethodMetadata(
					name: "trackItemSelected",
					parameters: [ParameterMetadata(externalLabel: nil, internalName: "identifier", type: "Int")],
					returnType: nil,
					isAsync: false,
					isThrowing: false,
					throwsType: nil,
					isConcurrent: false,
					hasGenericReturn: false,
					genericClause: nil
				),
			],
			properties: [],
			sourceFilePath: ""
		)

		let result = sut.generate(from: proto)

		#expect(result.contains("// MARK: - Reset"))
		#expect(result.contains("func reset()"))

		// Call counts reset
		#expect(result.contains("trackScreenViewedCallsCount = 0"))
		#expect(result.contains("trackItemSelectedCallsCount = 0"))

		// Single param reset
		#expect(result.contains("trackItemSelectedReceivedIdentifier = nil"))
		#expect(result.contains("trackItemSelectedReceivedInvocations = []"))
	}

	@Test("Generates reset that preserves configuration properties")
	func resetPreservesConfiguration() {
		let proto = ProtocolMetadata(
			name: "FooRepositoryContract",
			accessLevel: "",
			isNonisolated: true,
			inheritedTypes: ["Sendable"],
			methods: [
				MethodMetadata(
					name: "getItem",
					parameters: [],
					returnType: "Item",
					isAsync: true,
					isThrowing: true,
					throwsType: "ItemError",
					isConcurrent: true,
					hasGenericReturn: false,
					genericClause: nil
				),
				MethodMetadata(
					name: "fetchData",
					parameters: [],
					returnType: "Data",
					isAsync: true,
					isThrowing: true,
					throwsType: nil,
					isConcurrent: true,
					hasGenericReturn: false,
					genericClause: nil
				),
			],
			properties: [],
			sourceFilePath: ""
		)

		let result = sut.generate(from: proto)

		// Extract the reset function body
		let resetRange = result.range(of: "func reset()")!
		let resetBody = String(result[resetRange.lowerBound...])

		// Reset clears tracking
		#expect(resetBody.contains("getItemCallsCount = 0"))
		#expect(resetBody.contains("fetchDataCallsCount = 0"))

		// Reset does NOT clear ReturnValue or Closure
		#expect(!resetBody.contains("getItemReturnValue = nil"))
		#expect(!resetBody.contains("fetchDataReturnValue = nil"))
		#expect(!resetBody.contains("getItemClosure = nil"))
		#expect(!resetBody.contains("fetchDataClosure = nil"))
	}

	// MARK: - ReturnValue Types

	@Test("Generates Result ReturnValue for typed-throws method")
	func resultReturnValueForTypedThrows() {
		let proto = ProtocolMetadata(
			name: "FooUseCaseContract",
			accessLevel: "",
			isNonisolated: false,
			inheritedTypes: ["Sendable"],
			methods: [
				MethodMetadata(
					name: "execute",
					parameters: [ParameterMetadata(externalLabel: nil, internalName: "identifier", type: "Int")],
					returnType: "String",
					isAsync: true,
					isThrowing: true,
					throwsType: "FooError",
					isConcurrent: false,
					hasGenericReturn: false,
					genericClause: nil
				),
			],
			properties: [],
			sourceFilePath: ""
		)

		let result = sut.generate(from: proto)

		#expect(result.contains("var executeReturnValue: Result<String, FooError>?"))
		#expect(result.contains("return try returnValue.get()"))
		#expect(!result.contains("executeThrowableError"))
	}

	@Test("Generates Result ReturnValue for untyped throws using any Error")
	func resultReturnValueForUntypedThrows() {
		let proto = ProtocolMetadata(
			name: "FooContract",
			accessLevel: "",
			isNonisolated: true,
			inheritedTypes: ["Sendable"],
			methods: [
				MethodMetadata(
					name: "fetch",
					parameters: [],
					returnType: "String",
					isAsync: true,
					isThrowing: true,
					throwsType: nil,
					isConcurrent: true,
					hasGenericReturn: false,
					genericClause: nil
				),
			],
			properties: [],
			sourceFilePath: ""
		)

		let result = sut.generate(from: proto)
		#expect(result.contains("var fetchReturnValue: Result<String, any Error>?"))
		#expect(!result.contains("fetchThrowableError"))
	}

	@Test("Generates plain ReturnValue for non-throwing method")
	func plainReturnValueForNonThrowing() {
		let proto = ProtocolMetadata(
			name: "FooContract",
			accessLevel: "",
			isNonisolated: false,
			inheritedTypes: [],
			methods: [
				MethodMetadata(
					name: "getValue",
					parameters: [],
					returnType: "String",
					isAsync: false,
					isThrowing: false,
					throwsType: nil,
					isConcurrent: false,
					hasGenericReturn: false,
					genericClause: nil
				),
			],
			properties: [],
			sourceFilePath: ""
		)

		let result = sut.generate(from: proto)
		#expect(result.contains("var getValueReturnValue: String?"))
		#expect(!result.contains("Result<"))
	}

	@Test("Generates ThrowableError for void throwing method")
	func throwableErrorForVoidThrowing() {
		let proto = ProtocolMetadata(
			name: "FooContract",
			accessLevel: "",
			isNonisolated: false,
			inheritedTypes: [],
			methods: [
				MethodMetadata(
					name: "execute",
					parameters: [],
					returnType: nil,
					isAsync: true,
					isThrowing: true,
					throwsType: "FooError",
					isConcurrent: false,
					hasGenericReturn: false,
					genericClause: nil
				),
			],
			properties: [],
			sourceFilePath: ""
		)

		let result = sut.generate(from: proto)
		#expect(result.contains("var executeThrowableError: (FooError)?"))
		#expect(result.contains("if let error = executeThrowableError { throw error }"))
		#expect(!result.contains("Result<"))
	}

	// MARK: - Combined File

	@Test("Generates combined file with deduplicated imports and multiple mocks")
	func combinedFile() {
		let proto1 = ProtocolMetadata(
			name: "FooTrackerContract",
			accessLevel: "",
			isNonisolated: false,
			inheritedTypes: [],
			methods: [
				MethodMetadata(
					name: "trackScreenViewed",
					parameters: [],
					returnType: nil,
					isAsync: false,
					isThrowing: false,
					throwsType: nil,
					isConcurrent: false,
					hasGenericReturn: false,
					genericClause: nil
				),
			],
			properties: [],
			sourceFilePath: "",
			sourceImports: ["import Foundation", "import UIKit"]
		)
		let proto2 = ProtocolMetadata(
			name: "BarNavigatorContract",
			accessLevel: "",
			isNonisolated: false,
			inheritedTypes: [],
			methods: [
				MethodMetadata(
					name: "navigateToDetail",
					parameters: [],
					returnType: nil,
					isAsync: false,
					isThrowing: false,
					throwsType: nil,
					isConcurrent: false,
					hasGenericReturn: false,
					genericClause: nil
				),
			],
			properties: [],
			sourceFilePath: "",
			sourceImports: ["import Foundation", "import UIKit"]
		)

		let result = sut.generateCombinedFile(from: [proto1, proto2], isPublic: false)

		// Single header
		let headerCount = result.components(separatedBy: "// Auto-generated by SwiftGenerator").count - 1
		#expect(headerCount == 1)

		// Single import block (deduplicated)
		let uikitCount = result.components(separatedBy: "import UIKit").count - 1
		#expect(uikitCount == 1)

		// @testable import for internal
		#expect(result.contains("@testable import ChallengeCharacter"))

		// Both mocks present
		#expect(result.contains("final class FooTrackerMock: FooTrackerContract"))
		#expect(result.contains("final class BarNavigatorMock: BarNavigatorContract"))
	}

	@Test("Generates combined file with public import for public mocks")
	func combinedFilePublic() {
		let proto = ProtocolMetadata(
			name: "NavigatorContract",
			accessLevel: "public",
			isNonisolated: false,
			inheritedTypes: [],
			methods: [],
			properties: [],
			sourceFilePath: ""
		)

		let result = publicSut.generateCombinedFile(from: [proto], isPublic: true)

		#expect(result.contains("import ChallengeCore"))
		#expect(!result.contains("@testable"))
		#expect(result.contains("public final class NavigatorMock: NavigatorContract"))
	}

	// MARK: - Helpers

	private func makeProto(name: String) -> ProtocolMetadata {
		ProtocolMetadata(
			name: name,
			accessLevel: "",
			isNonisolated: false,
			inheritedTypes: [],
			methods: [],
			properties: [],
			sourceFilePath: ""
		)
	}
}
